[package]
name = "rutabaga_gfx"
version = "0.1.6"
authors = ["The ChromiumOS Authors + Android Open Source Project"]
edition = "2021"
description = "Handling virtio-gpu protocols"
license-file = "LICENSE"

[features]
gfxstream = []
gfxstream_stub = []
virgl_renderer = []
minigbm = []
# Vulkano features are just a prototype and not integrated yet into the ChromeOS build system.
vulkano = ["dep:vulkano"]
x = []

[dependencies]
anyhow = { workspace = true }
cfg-if = { workspace = true }
libc = { workspace = true }
remain = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
thiserror = { workspace = true }
zerocopy = { version = "0.8.13", features = ["derive"] }

log = "0.4"

# To build latest Vulkano, change version to git = "https://github.com/vulkano-rs/vulkano.git"
vulkano = { version = "0.33.0", optional = true }

[target.'cfg(any(target_os = "android", target_os = "linux"))'.dependencies]
nix = { version = "0.29", features = ["event", "feature", "fs", "mman", "socket", "uio", "ioctl"] }

[target.'cfg(windows)'.dependencies]
winapi = {version = "0.3", features = ["winnt", "handleapi", "processthreadsapi", "winbase"]}

[build-dependencies]
pkg-config = "0.3"
anyhow = { workspace = true }

[dev-dependencies]
tempfile = "3"
