[package]
name = "rutabaga_gfx"
version = "0.1.0"
authors = ["The Chromium OS Authors"]
edition = "2018"

[features]
gfxstream = []
virgl_renderer = []
virgl_renderer_next = []

[dependencies]
data_model = { path = "../data_model" }
libc = "*"
base = { path = "../base" }
